### ISSUE TITLE
[Task] Implement landing page

### ISSUE THREAD

**Issue by JasonBarahan** [cssu/orientation-stamp-rally#6]
### Task

We need a landing page to advertise out event. This is ideally done sooner than later as we can use this as part of our marketing materials.

Can be done in consultancy with our graphics team.

### Steps

- [ ] cook some banger designs on Figma
- [ ] pass the review stage
- [ ] start implementing the front end
- [ ] create unit tests
- [ ] pass the review stage
